version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_USER: 'demo'
      MYSQL_PASSWORD: '1234'
      MYSQL_DATABASE: job_db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql

  admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '3307:80'

  sonarqube:
    image: sonarqube:8.9.7-community
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    ports:
      - '9000:9000'

  project:
    image: buildstabilityindicator
    restart: always
    depends_on:
      - db
    build:
      context: ./projectd20
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://db:3306/job_db",
          "spring.datasource.username" : "demo",
          "spring.datasource.password" : "1234",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    ports:
      - '8080:8080'

volumes:
  db: