const externals = {
  apps: [{
    path: "app-1",
    entry: "App1"
  }],
  components: {
    default: [],
    shareable: [{
      path: "panel-component",
      entry: "PanelComponent"
    }, {
      path: "displayarea-component",
      entry: "DisplayareaComponent"
    }, {
      path: "job1component",
      entry: "Job1component"
    }, {
      path: "main-component",
      entry: "MainComponent"
    }, {
      path: "job2-main-component",
      entry: "Job2MainComponent"
    }, {
      path: "job3-main-component",
      entry: "Job3MainComponent"
    }, {
      path: "job4-main-component",
      entry: "Job4MainComponent"
    }, {
      path: "job5-main-component",
      entry: "Job5MainComponent"
    }, {
      path: "job6-main-component",
      entry: "Job6MainComponent"
    }, {
      path: "job7-main-component",
      entry: "Job7MainComponent"
    }, {
      path: "job8-main-component",
      entry: "Job8MainComponent"
    }, {
      path: "job9-main-component",
      entry: "Job9MainComponent"
    }, {
      path: "job10-main-component",
      entry: "Job10MainComponent"
    }, {
      path: "job2-displayarea-component",
      entry: "Job2DisplayareaComponent"
    }, {
      path: "calender-component",
      entry: "CalenderComponent"
    }, {
      path: "job3-displayarea-component",
      entry: "Job3DisplayareaComponent"
    }, {
      path: "job3-displayarea-component",
      entry: "Job3DisplayareaComponent"
    }, {
      path: "job4-displayarea-component",
      entry: "Job4DisplayareaComponent"
    }, {
      path: "job5-displayarea-component",
      entry: "Job5DisplayareaComponent"
    }, {
      path: "job6-displayarea-component",
      entry: "Job6DisplayareaComponent"
    }, {
      path: "job7-displayarea-component",
      entry: "Job7DisplayareaComponent"
    }, {
      path: "job8-displayarea-component",
      entry: "Job8DisplayareaComponent"
    }, {
      path: "job9-displayarea-component",
      entry: "Job9DisplayareaComponent"
    }, {
      path: "job10-displayarea-component",
      entry: "Job10DisplayareaComponent"
    }]
  },
  panels: [],
  plugins: []
};
module.exports = externals;